###
'quality_assessment.R contains the code used to process genome quality data generated by QUAST and CheckM'
###

library(reshape2)
library(dplyr)
library(ggplot2)
library(stringr)
#plotting
library(cowplot)
library(ggsci)
library(scales)
library(RColorBrewer)
library(egg)
#Tree
library(ape)
library(ggrepel)
library(ggtree)
library(ggstance)
library(phytools)
library(phylogram)
library(dendextend)
library(treespace)
#ASR
library(ggimage)



main_path <- '/Users/owlex/Dropbox/Documents/Northwestern/Hartmann_Lab/enr_comparison_project/manuscript/ismej_submission/github/fabv_paper/quality_assessments'



#### Section 0 ####
#### CheckM and QUAST quality check for 160 type strains, 30 study isolates, and c japonicus outgroup
#### output is df_checkm, which contains all 
section_0_path <- paste(main_path,'section_0',sep='/')
setwd(section_0_path)
#
## Read in checkm outputs
df1 <- read.csv('checkm_output.txt',sep='\t')
df2 <- read.csv('checkm_output2.txt',sep='\t')
#
df_meta <- read.csv('processed_genomes_metadata.csv')
df_checkm <- rbind(df1,df2)
df_checkm <- df_checkm%>%mutate(bID=paste(Bin.Id,'.fna',sep=''))
df_checkm <- merge(df_checkm,df_meta,by.x='bID',by.y='filename')
write.csv(df_checkm,'checkm_quast_metrics.csv')

#### Section 1 ####
#### CheckM and QUAST quality check for 8,747 genomes downloaded from NCBI. A subset of the original ~9,000 genommes downloaded was already filtered for contigs
###
#### output is 'large_ani_analysis.csv', which is the curated list of genomes that pass the metrics and also all the type strains
section_1_path <- paste(main_path,'section_1',sep='/')
setwd(section_1_path)
#
## Designate the representative species genomes in the df_meta dataset
df_meta <- read.csv('processed_genomes_metadata.csv')
df_rep <- read.csv('processed_genomes_metadata_typeestrains.csv')%>%filter(source=='REFSEQ')

## filter for quast metrics
df_meta <- df_meta%>%mutate(representative=case_when(filename%in%df_rep$filename~1,TRUE~0))
df_meta <- df_meta%>%filter((total_contigs<=300 & N50>=10000)|representative==1)
## prepare for merging
df_meta <- df_meta%>%mutate(filename2=str_replace(filename,'.fna',''))
#
## Read in compiled checkM results 
df_checkm <- read.csv('refseq_checkm_complete.csv')
## merge datasets
df_meta <- merge(df_meta,df_checkm,by.x='filename2',by.y='Bin.Id')
## Filter for checkM scores
df_meta <- df_meta%>%mutate(overallquality=Completeness-(5*Contamination))
df_meta <- df_meta%>%filter((overallquality>=50&Completeness>=90&Contamination<=10)|representative==1)
## write to file
write.csv(df_meta,'large_ani_analysis.csv',row.names=FALSE)


#### Section 2 #### 
#### Make a large genome strain datatable for publication 
#### and Generate figure with compelteness, conitg, and n50 statistics for all (7,163) genomes in study
section_2_path <- paste(main_path,'section_2',sep='/')
setwd(section_2_path)
#
####
# Contains all metadata, quast, and checkm info for the ~8000 ncbi refseq genomes
df_compiled <- read.csv('large_ani_analysis.csv')

## Filtering for desired checkM values
df_compiled <- df_compiled%>%mutate(overallquality=Completeness-(5*Contamination))
nrow(df_compiled%>%filter(representative==1))
df_compiled <- df_compiled%>%filter((overallquality>=50&Completeness>=90&Contamination<=10)|(representative==1))
nrow(df_compiled%>%filter(representative==1))

df_metapass <- read.csv('pass_largegenomesanalysis.csv')
df_metapass <- merge(df_compiled,df_metapass,by.x='filename',by.y='filename',all.y=TRUE)
df_metapass <- df_metapass%>%select(filename,id,species,mod_species,fabv_pa,type,total_contigs,total_length,N50,Completeness,Contamination,overallquality,description)%>%
  rename(refseq_species=species,ANI_species_group=mod_species,fabv_detected=fabv_pa,type_strain=type,overall_quality=overallquality,refseq_description=description)

# Writing the compiled df_metapass dataframe
write.csv(df_metapass,'filtered_processed_genomes_metadata.csv',row.names=FALSE)


#### Generate figure with completeness, conitg, and n50 statistics for all (7,134) genomes in study

#
## Reading in study isolate checkm and quast data
df_isolate <- read.csv('checkm_output_modified.txt',sep='\t')
df_isolatequast <- read.csv('processed_genomes_metadata.csv')%>%filter(source=='USER')%>%mutate(representative=2)
df_isolate <- merge(df_isolate,df_isolatequast,by.x='Bin.Id',by.y='id')
df_isolate <- df_isolate%>%mutate(overallquality=Completeness-(5*Contamination))
#
## Merge isolate data with refseq/type strain data
df_compiled <- df_compiled%>%select(cleaned_filename,representative,Completeness,Contamination,total_contigs,N50,overallquality)
df_isolate <- df_isolate%>%select(cleaned_filename,representative,Completeness,Contamination,total_contigs,N50,overallquality)
df_compiled <- rbind(df_compiled,df_isolate)
df_compiled <- df_compiled%>%filter()


p1 <- ggplot(df_compiled,aes(x=as.factor(representative),y=Completeness))+
  #geom_violin(color='maroon')+
  geom_point(position=position_jitter(),alpha=.2)+
  geom_violin(color='lightblue',alpha=.1)+theme_classic()+
  theme(axis.title.x = element_text(size = 0),axis.title.y = element_text(size = 30),
        axis.text.x = element_text(size = 30,color='white'),axis.text.y = element_text(size = 30),legend.position = 'none')+
  scale_x_discrete(labels=c('0'='RefSeq\nGenomes','1'='Type\nStrains','2'='Study\nIsolates'))
  #geom_segment(aes(x=0.5,xend=1.5,y=90,yend=90),color='orange',linetype='dashed')#(yintercept=90.0,linetype='dashed',color='lightblue',size=1,alpha=0.8)
  
p2 <- ggplot(df_compiled,aes(x=as.factor(representative),y=Contamination))+
  #geom_violin()+
  geom_point(position=position_jitter(),alpha=.2)+
  geom_violin(color='lightblue',alpha=.1)+theme_classic()+
  theme(axis.title.x = element_text(size = 0),axis.title.y = element_text(size = 30),
        axis.text.x = element_text(size = 30,color='white'),axis.text.y = element_text(size = 30),legend.position = 'none')+
  scale_x_discrete(labels=c('0'='RefSeq\nGenomes','1'='Type\nStrains','2'='Study\nIsolates'))#+
#geom_segment(aes(x=0.5,xend=1.5,y=10,yend=10),color='orange',linetype='dashed')#(yintercept=90.0,linetype='dashed',color='lightblue',size=1,alpha=0.8)


p3 <- ggplot(df_compiled,aes(x=as.factor(representative),y=total_contigs))+
  #geom_violin()+
  geom_point(position=position_jitter(),alpha=.2)+
  geom_violin(color='lightblue',alpha=.1)+theme_classic()+
  theme(axis.title.x = element_text(size = 0),axis.title.y = element_text(size = 30),
        axis.text.x = element_text(size = 30,color='white'),axis.text.y = element_text(size = 30),legend.position = 'none')+
  scale_x_discrete(labels=c('0'='RefSeq\nGenomes','1'='Type\nStrains','2'='Study\nIsolates'))#+
#geom_segment(aes(x=0.5,xend=1.5,y=300,yend=300),color='orange',linetype='dashed')#(yintercept=90.0,linetype='dashed',color='lightblue',size=1,alpha=0.8)

p4 <- ggplot(df_compiled,aes(x=as.factor(representative),y=N50))+
  #geom_violin()+
  geom_point(position=position_jitter(),alpha=.2)+
  geom_violin(color='lightblue',alpha=.1)+theme_classic()+
  theme(axis.title.x = element_text(size = 0),axis.title.y = element_text(size = 30),
        axis.text.x = element_text(size = 30),axis.text.y = element_text(size = 30),legend.position = 'none')+
  scale_x_discrete(labels=c('0'='RefSeq\nGenomes','1'='Type\nStrains','2'='Study\nIsolates'))#+
#geom_segment(aes(x=0.5,xend=1.5,y=10000,yend=10000),color='orange',linetype='dashed')#(yintercept=90.0,linetype='dashed',color='lightblue',size=1,alpha=0.8)

t <- ggarrange(p1,p2,p3,p4,nrow=4,ncol=1)

save_plot('sec2_genome_quality_stats.png',t,base_height=16,base_aspect_ratio = 1.4)













